name: Maven Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/*.java', '**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Send logs via email
        if: always()  # Ensures that the email will be sent even if the previous steps failed
        uses: dawidd6/action-send-mail@v3
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 587
          smtp-user: ${{ secrets.SMTP_USER }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          from: your-email@gmail.com  # Add sender email here (e.g., your Gmail email address)
          to: annelinejcbs@gmail.com  # Replace with the recipient's email address
          subject: "GitHub Actions Logs"
          body: |
            The GitHub Actions logs are attached below.
          attachments: /home/runner/work/petfinder-api-tests/petfinder-api-tests/target/surefire-reports/*.xml
